### ISSUE TITLE
Lock Nav bar

### ISSUE THREAD

**Issue by cwatry** [ryankinzer/nptfisheries#9]
Looking into code to lock the nav bar at top of screen for all pages

**Comment by ryankinzer** [comment]
Fix position to top of the screen, fix active page highlighting to correct page, and increase highlighting for hoover text.

**Comment by ryankinzer** [comment]
commit nav_fixed d48c614 fixes navbar position and update active links, hoover highlighting was not changed and controlled with current bootstrap css
